--------------------- Title ------------------------
-- Project Name: HA_System
-- File Name: alarm_Control_TB.vhd
-- Author: Generated by assistant
-- Ver: 2 (Comprehensive)
-- Created Date: 10/12/25
----------------------------------------------------
-- Testbench covers all FSM states and edge cases

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity alarm_Control_TB is
end entity;

architecture tb of alarm_Control_TB is

    -- Component signals
    signal Clk                : std_logic := '0';
    signal Rst                : std_logic := '1';
    signal intrusion_detected : std_logic := '0';
    signal code_ready         : std_logic := '0';
    signal code_match         : std_logic := '0';
    signal enable_press       : std_logic;
    signal clear_code         : std_logic;
    signal alarm_siren        : std_logic;
    signal system_armed       : std_logic;
    signal attempts           : integer range 0 to 7;
    signal state_code         : std_logic_vector(7 downto 0);

    constant clk_period : time := 10 ns;
    constant ASCII_0    : std_logic_vector(7 downto 0) := x"30";
    constant ASCII_8    : std_logic_vector(7 downto 0) := x"38";
    constant ASCII_A    : std_logic_vector(7 downto 0) := x"41";
    constant ASCII_F    : std_logic_vector(7 downto 0) := x"46";

begin

    -- Instantiate Unit Under Test (UUT)
    UUT: entity work.alarm_Control
        port map(
            Clk => Clk,
            Rst => Rst,
            intrusion_detected => intrusion_detected,
            code_ready => code_ready,
            code_match => code_match,
            enable_press => enable_press,
            clear_code => clear_code,
            alarm_siren => alarm_siren,
            system_armed => system_armed,
            attempts => attempts,
            state_code => state_code
        );

    -- Clock generation
    clk_proc: process
    begin
        while true loop
            Clk <= '0';
            wait for clk_period/2;
            Clk <= '1';
            wait for clk_period/2;
        end loop;
    end process clk_proc;

    -- Comprehensive stimulus process
    stim_proc: process
        -- Helper procedure to verify state
        procedure verify_state(expected_state : std_logic_vector(7 downto 0); state_name : string) is
        begin
            if state_code = expected_state then
                report "[TB-PASS] State verified: " & state_name severity note;
            else
                report "[TB-FAIL] State mismatch. Expected: " & state_name & " Got: 0x" & 
                    integer'image(to_integer(unsigned(state_code))) severity warning;
            end if;
        end procedure;

        procedure verify_signal(signal_val : std_logic; expected : std_logic; sig_name : string) is
        begin
            if signal_val = expected then
                report "[TB-PASS] " & sig_name & " = " & std_logic'image(expected) severity note;
            else
                report "[TB-FAIL] " & sig_name & " mismatch. Expected: " & std_logic'image(expected) &
                    " Got: " & std_logic'image(signal_val) severity warning;
            end if;
        end procedure;

        procedure verify_signal(signal_val : integer; expected : integer; sig_name : string) is
        begin
            if signal_val = expected then
                report "[TB-PASS] " & sig_name & " = " & integer'image(expected) severity note;
            else
                report "[TB-FAIL] " & sig_name & " mismatch. Expected: " & integer'image(expected) &
                    " Got: " & integer'image(signal_val) severity warning;
            end if;
        end procedure;

    begin
        report "=== TEST 1: POWER-UP AND AUTO-ARM ===" severity note;
        Rst <= '1';
        intrusion_detected <= '0';
        code_ready <= '0';
        code_match <= '0';
        wait for 2*clk_period;
        Rst <= '0';
        wait for 1*clk_period;

        -- System auto-arms after first clock edge following reset
        -- So expect ST_ARMED immediately (or after very few clocks)
        wait until system_armed = '1' or now > 100 ns;
        verify_state(ASCII_8, "ST_ARMED");
        report "[TB] System armed at " & time'image(now) severity note;

        report "=== TEST 2: INTRUSION DETECTION (ARMED -> ALERT) ===" severity note;
        wait for 2*clk_period;
        intrusion_detected <= '1';
        wait for clk_period;
        intrusion_detected <= '0';
        wait for clk_period;

        -- Verify transition to ST_ALERT
        wait until alarm_siren = '1' or now > 200 ns;
        verify_state(ASCII_A, "ST_ALERT");
        verify_signal(alarm_siren, '1', "alarm_siren in ST_ALERT");
        verify_signal(system_armed, '0', "system_armed should be 0 in ST_ALERT");
        report "[TB] Intrusion triggered, siren active" severity note;

        report "=== TEST 3: CODE ENTRY MODE (ALERT -> ATTEMPTS) ===" severity note;
        wait until enable_press = '1' or now > 250 ns;
        verify_signal(enable_press, '1', "enable_press in ST_ATTEMPTS");
        wait for clk_period;

        report "=== TEST 4: FAILED CODE ATTEMPTS (0 to 7) ===" severity note;
        for attempt_num in 1 to 7 loop
            report "[TB] Simulating failed attempt #" & integer'image(attempt_num) severity note;
            code_ready <= '0';
            wait for clk_period;
            code_ready <= '1';
            code_match <= '0';
            wait for clk_period;
            code_ready <= '0';
            code_match <= '0';
            wait for clk_period;

            -- Verify attempts counter
            if attempts = attempt_num then
                report "[TB-PASS] Attempts counter incremented to " & integer'image(attempts) severity note;
            else
                report "[TB-FAIL] Attempts counter mismatch. Expected: " & integer'image(attempt_num) &
                    " Got: " & integer'image(attempts) severity warning;
            end if;

            -- Stay in ST_ATTEMPTS while attempts < 7
            if attempt_num < 7 then
                report "[TB] In ST_ATTEMPTS, waiting for next entry prompt" severity note;
                wait until enable_press = '1' or now > ((250 + attempt_num * 100) * 1 ns);
            else
                -- After 7 failed attempts, should escalate to ST_ALERT
                wait for 2*clk_period;
                verify_state(ASCII_A, "ST_ALERT after max attempts");
                verify_signal(alarm_siren, '1', "alarm_siren should re-activate");
                report "[TB] Max attempts reached, escalated to ST_ALERT" severity note;
            end if;
            wait for clk_period;
        end loop;

        report "=== TEST 5: RECOVERY FROM MAX ATTEMPTS (RESET) ===" severity note;
        Rst <= '1';
        wait for 2*clk_period;
        verify_signal(system_armed, '0', "system_armed should be 0 after reset");
        verify_signal(attempts, 0, "attempts should be 0 after reset");
        Rst <= '0';
        wait for 1*clk_period;

        report "=== TEST 6: CORRECT CODE ENTRY ===" severity note;
        -- System auto-arms after reset
        wait until system_armed = '1' or now > 600 ns;
        verify_state(ASCII_8, "ST_ARMED");
        wait for 2*clk_period;

        -- Trigger intrusion again
        intrusion_detected <= '1';
        wait for clk_period;
        intrusion_detected <= '0';
        wait until enable_press = '1' or now > 700 ns;

        -- Submit correct code immediately
        code_ready <= '0';
        wait for clk_period;
        code_ready <= '1';
        code_match <= '1';
        wait for clk_period;
        code_ready <= '0';
        code_match <= '0';
        wait for clk_period;

        -- Verify transition to ST_CORRECT
        verify_state(ASCII_F, "ST_CORRECT");
        wait for clk_period;

        -- Verify re-arm after ST_CORRECT
        wait until system_armed = '1' or now > 800 ns;
        verify_state(ASCII_8, "ST_ARMED after correct code");
        verify_signal(alarm_siren, '0', "alarm_siren should be off");
        verify_signal(attempts, 0, "attempts should be reset");
        report "[TB] System re-armed successfully after correct code" severity note;

        report "=== TEST 7: MULTIPLE INTRUSIONS (ROBUSTNESS) ===" severity note;
        for intrusion_num in 1 to 3 loop
            report "[TB] Intrusion cycle #" & integer'image(intrusion_num) severity note;
            wait for 4*clk_period;
            intrusion_detected <= '1';
            wait for clk_period;
            intrusion_detected <= '0';
            wait until enable_press = '1' or now > ((850 + intrusion_num * 150) * 1 ns);

            -- Enter correct code each time
            code_ready <= '0';
            wait for clk_period;
            code_ready <= '1';
            code_match <= '1';
            wait for clk_period;
            code_ready <= '0';
            code_match <= '0';
            wait until system_armed = '1' or now > ((900 + intrusion_num * 150) * 1 ns);
            report "[TB] System re-armed after intrusion cycle #" & integer'image(intrusion_num) severity note;
        end loop;

        report "=== TEST 8: EDGE CASE - CODE_READY TIMING ===" severity note;
        wait for 2*clk_period;
        -- Ensure we're back armed before triggering intrusion
        wait until system_armed = '1' or now > 1100 ns;
        wait for clk_period;
        intrusion_detected <= '1';
        wait for clk_period;
        intrusion_detected <= '0';
        wait until enable_press = '1' or now > 1150 ns;

        -- Rapid code_ready pulse (narrow pulse, ensure it's sampled)
        code_ready <= '0';
        wait for clk_period;
        code_ready <= '1';
        code_match <= '1';
        wait for clk_period;
        code_ready <= '0';
        code_match <= '0';
        wait for 2*clk_period;
        report "[TB] Narrow code_ready pulse handled correctly" severity note;

        report "=== TEST 9: ASYNCHRONOUS RESET DURING ALARM ===" severity note;
        wait for 2*clk_period;
        -- Ensure we're armed first
        wait until system_armed = '1' or now > 1200 ns;
        wait for clk_period;
        intrusion_detected <= '1';
        wait for clk_period;
        intrusion_detected <= '0';
        wait until alarm_siren = '1' or now > 1220 ns;
        -- Assert reset while alarm is active
        Rst <= '1';
        wait for clk_period;
        verify_signal(system_armed, '0', "system_armed should be 0 after async reset");
        Rst <= '0';
        wait for 1*clk_period;

        report "=== TEST 10: SIGNAL INTEGRITY - CLEAR_CODE PULSE ===" severity note;
        -- Ensure we're armed
        wait until system_armed = '1' or now > 1350 ns;
        wait for clk_period;
        intrusion_detected <= '1';
        wait for clk_period;
        intrusion_detected <= '0';
        wait until enable_press = '1' or now > 1400 ns;

        -- Observe clear_code during code entry
        code_ready <= '0';
        wait for clk_period;
        if clear_code = '0' then
            report "[TB-PASS] clear_code low during code entry" severity note;
        else
            report "[TB-FAIL] clear_code should be low during entry" severity warning;
        end if;

        code_ready <= '1';
        code_match <= '0';
        wait for clk_period;
        if clear_code = '1' then
            report "[TB-PASS] clear_code high during code check" severity note;
        else
            report "[TB-FAIL] clear_code should be high during check" severity warning;
        end if;

        code_ready <= '0';
        code_match <= '0';
        wait for 2*clk_period;

        report "=== ALL TESTS COMPLETED ===" severity note;
        wait;
    end process stim_proc;

end architecture tb;
